<table class="mb">
   <tr>
      <th class="mb-adminlCommands">ADMIN/MODERATOR COMMANDS</th>
      <th class="mb-adminlCommands">USAGE &amp; INFO</th>
   </tr>
   <tr>
      <td class="mb-usageBG">m.addemoji [url] [name]</td>
      <td class="mb-usageBG">Let's you add an emoji to the server via a URL</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.ban @user [reason]</td>
      <td class="mb-usageBG">Bans the tagged user and logs the reason (also send them a DM if they have DM's open)</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.blacklist @user</td>
      <td class="mb-usageBG">Prevents the tagged user from using MarksBot commands</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.check</td>
      <td class="mb-usageBG">Checks to see if any users have invite links in their status message</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.clearwarnings @user</td>
      <td class="mb-usageBG">Removes ALL warnings for that user</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.idban [id]</td>
      <td class="mb-usageBG">Bans a user by using the UID even if they are not in the server - example m.idban 272442568275525634</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.kick @user [reason]</td>
      <td class="mb-usageBG">Kicks the tagged user from the server and logs the reason (also send them a DM if they have DM's open)</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.mute @user</td>
      <td class="mb-usageBG">Mutes a user so they cannot speak (you are responsible for permissions etc)</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.prune [number 1-100]</td>
      <td class="mb-usageBG">Bulk delete messages up to 100 or m.prune @user bulk delete messages for the tagged user</td>
   </tr>
   <!--<tr>
      <td class="mb-usageBG">m.setprefix [new prefix]</td>
      
      <td class="mb-usageBG">Sets a new prefix for the current server - Example <code>m.setprefix t.</code></td>
      
      </tr> -->
   <tr>
      <td class="mb-usageBG">m.softban @user @user etc</td>
      <td class="mb-usageBG">Bans and immediately unbans the tagged user (s), removing 7 days of their messages</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.unblacklist @user</td>
      <td class="mb-usageBG">Allows a blacklisted user to use MarksBot commands again</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.unmute @user</td>
      <td class="mb-usageBG">Unmutes a muted user</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.warn @user [warn reason]</td>
      <td class="mb-usageBG">Issues the tagged user with a warning and logs it</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.warnings @user</td>
      <td class="mb-usageBG">Displays all warnings for the tagged user</td>
   </tr>
</table>
