<table class="mb">
  <tr>
    <th class="mb-generalCommands">GENERAL COMMANDS</th>
    <th class="mb-generalCommands">USAGE &amp; INFO</th>
  </tr>
  <tr>
    <td class="mb-usageBG">m.8ball [question]</td>
    <td class="mb-usageBG">Consults the magic 8ball - example m.8ball are you here? </td>
  </tr>
  <tr>
    <td class="mb-usageBG">m.ask [question]</td>
    <td class="mb-usageBG">Ask MarksBot a question - example m.ask is it raining outside?</td>
  </tr>
  <tr>
    <td class="mb-usageBG">m.avatar @user</td>
    <td class="mb-usageBG">Displays the avatar of the user you tagged or displays your own avatar if no user is tagged</td>
  </tr>
  <tr>
    <td class="mb-usageBG">m.bill</td>
    <td class="mb-usageBG">Generate a be like bill image</td>
  </tr>
  <tr>
    <td class="mb-usageBG">m.billme [name] [gender]</td>
    <td class="mb-usageBG">Generate a be like bill image with your name (m.billme Mark m | m.billme Abbie f)</td>
  </tr>
  <tr>
    <td class="mb-usageBG">m.bingo</td>
    <td class="mb-usageBG">Can be used when playing Bingo to help you scratch off your card</td>
  </tr>
  <tr>
    <td class="mb-usageBG">m.botemoji</td>
    <td class="mb-usageBG">Displays all the emoji the bot has access to</td>
  </tr>
  <tr>
    <tr>
    <td class="mb-usageBG">m.discord</td>
    <td class="mb-usageBG">Shows the current status of Discord</td>
  </tr>
    <td class="mb-usageBG">m.e [text]</td>
    <td class="mb-usageBG">Puts your text into an embed - example m.e Hello MarksBot</td>
  </tr>
    <tr>
    <td class="mb-usageBG">m.emoji</td>
    <td class="mb-usageBG">Displays the custom emoji on the server</td>
  </tr>
    <tr>
    <td class="mb-usageBG">m.emojisearch [text]</td>
    <td class="mb-usageBG">Search the bot for emoji matching the requested name</td>
  </tr>
   <tr>
    <td class="mb-usageBG">m.fc</td>
    <td class="mb-usageBG">Fingers crossed</td>
  </tr>
   <tr>
    <td class="mb-usageBG">m.fns</td>
    <td class="mb-usageBG">Shows the Fortnite Daily Shop</td>
  </tr>
   <tr>
    <td class="mb-usageBG">(*) m.fns2</td>
	<td class="mb-usageBG">Shows an interactive version of the Fortnite Daily Shop</td>
  </tr>
  <!--   <tr>
    <td class="mb-disabled"><s>m.gc [text]</s></td>
    <td class="mb-disabled">CURRENTLY DISABLED <s>Sends a global chat message - example m.gc Hello, what server are you in?</s></td>
  </tr> -->
    <tr>
    <td class="mb-usageBG">m.help</td>
    <td class="mb-usageBG">Displays the command list</td>
  </tr>
    <tr>
    <td class="mb-usageBG">m.invite</td>
    <td class="mb-usageBG">Displays the invite link so you can invite MarksBot to your server</td>
  </tr>
    <tr>
    <td class="mb-usageBG">m.info</td>
    <td class="mb-usageBG">Displays how many servers MarksBot is on and how many users it is serving</td>
  </tr>
    <tr>
    <td class="mb-usageBG">m.lastseen @user</td>
    <td class="mb-usageBG">Displays when the tagged user was last active [shows "undefined" if the users has not been active since the bot last restarted]</td>
  </tr>
    <tr>
    <td class="mb-usageBG">m.morsecode [text]</td>
    <td class="mb-usageBG">Converts your message into morsecode - example m.morsecode sos</td>
  </tr>
    <tr>
    <td class="mb-usageBG">m.mybill [text]</td>
    <td class="mb-usageBG">Put your own text on Bill</td>
  </tr>
    <tr>
    <td class="mb-usageBG">m.ping</td>
    <td class="mb-usageBG">Check if the bot is reponding</td>
  </tr>
    <tr>
    <td class="mb-usageBG">m.quiz</td>
    <td class="mb-usageBG">Answer a general knowledge question</td>
  </tr>
    <tr>
    <td class="mb-usageBG">m.rc </td>
    <td class="mb-usageBG">Generates a rancom color and displays the DEC and HEX values</td>
  </tr>
   <tr>
    <td class="mb-usageBG">m.someone</td>
    <td class="mb-usageBG">Picks a random server member</td>
  </tr>
    <tr>
    <td class="mb-usageBG">m.spinner</td>
    <td class="mb-usageBG">How long will it spin for?</td>
  </tr>
    <tr>
    <td class="mb-usageBG">m.serverinfo</td>
    <td class="mb-usageBG">Displays current server information</td>
  </tr>
    <tr>
    <td class="mb-usageBG">m.userinfo @user</td>
    <td class="mb-usageBG">Displays information about the tagged users account or your own information if no user is tagged</td>
  </tr>
    <tr>
    <td class="mb-usageBG">m.uptime</td>
    <td class="mb-usageBG">Displays how long MarksBot has been up for since it's last reboot</td>
  </tr>
  <tr>
    <td class="mb-usageBG">m.vote</td>
    <td class="mb-usageBG">Checks if you are able to upvote MarksBot</td>
  </tr>
   <tr>
    <td class="mb-usageBG">m.yesno [text]</td>
    <td class="mb-usageBG">Ask a question and the bot will decide yes or no - example Should I make food?</td>
  </tr>
</table>
<br>
<table class="mb">
  <tr>
    <th class="mb-adminlCommands">ADMIN/MODERATOR COMMANDS</th>
    <th class="mb-adminlCommands">USAGE &amp; INFO</th>
  </tr>
  <tr>
    <td class="mb-usageBG">m.ban @user [reason]</td>
    <td class="mb-usageBG">Bans the tagged user and logs the reason (also send them a DM if they have DM's open)</td>
  </tr>
  <tr>
    <td class="mb-usageBG">m.blacklist @user</td>
    <td class="mb-usageBG">Prevents the tagged user from using MarksBot commands</td>
  </tr>
  <tr>
    <td class="mb-usageBG">m.check</td>
    <td class="mb-usageBG">Checks to see if any users have invite links in their status message</td>
  </tr>
  <tr>
    <td class="mb-usageBG">m.clearwarnings @user</td>
    <td class="mb-usageBG">Removes ALL warnings for that user</td>
  </tr>
  <tr>
    <td class="mb-usageBG">m.idban [id]</td>
    <td class="mb-usageBG">Bans a user by using the UID even if they are not in the server - example m.idban 272442568275525634</td>
  </tr>
  <tr>
    <td class="mb-usageBG">m.kick @user [reason]</td>
    <td class="mb-usageBG">Kicks the tagged user from the server and logs the reason (also send them a DM if they have DM's open)</td>
  </tr>
  <tr>
    <td class="mb-usageBG">m.mute @user</td>
    <td class="mb-usageBG">Mutes a user so they cannot speak (you are responsible for permissions etc)</td>
  </tr>
   <tr>
    <td class="mb-usageBG">m.prune [number 1-100]</td>
    <td class="mb-usageBG">Bulk delete messages up to 100 or m.prune @user bulk delete messages for the tagged user</td>
  </tr>
    <tr>
    <td class="mb-usageBG">m.softban @user @user etc</td>
    <td class="mb-usageBG">Bans and immediately unbans the tagged user (s), removing 7 days of their messages</td>
  </tr>
  <tr>
    <td class="mb-usageBG">m.unblacklist @user</td>
    <td class="mb-usageBG">Allows a blacklisted user to use MarksBot commands again</td>
  </tr>
  <tr>
    <td class="mb-usageBG">m.unmute @user</td>
    <td class="mb-usageBG">Unmutes a muted user</td>
  </tr>
  <tr>
    <td class="mb-usageBG">m.warn @user [warn reason]</td>
    <td class="mb-usageBG">Issues the tagged user with a warning and logs it</td>
  </tr>
  <tr>
    <td class="mb-usageBG">m.warnings @user</td>
    <td class="mb-usageBG">Displays all warnings for the tagged user</td>
  </tr>
</table>
<br>
<table class="mb">
  <tr>
    <th class="mb-userRequested">USER REQUESTED COMMANDS</th>
    <th class="mb-userRequested">USAGE &amp; INFO</th>
  </tr>
  <tr>
    <td class="mb-usageBG">m.google [search term]</td>
    <td class="mb-usageBG">Use MarksBot to search Google - example m.google download discord</td>
  </tr>
   <tr>
   <td class="mb-usageBG">m.imdb [movie] </td>
    <td class="mb-usageBG">Displays information about the movie you request</td>
  </tr>
   <tr>
   <td class="mb-usageBG">m.ipcheck [ip] </td>
    <td class="mb-usageBG">Displays information about the IP address you provided (can be sent to dm's or channel)</td>
  </tr>
  <tr>
    <td class="mb-usageBG">m.say [text] </td>
    <td class="mb-usageBG">MarksBot will repeat what you say to it</td>
  </tr>
  <tr>
    <td class="mb-usageBG">m.ud [word]</td>
    <td class="mb-usageBG">Search the urban dictionary - example m.ud test</td>
  </tr>
   <!-- <tr>
    <td class="mb-usageBG">m.yip</td>
    <td class="mb-usageBG">Queries the IP Stack API and DM's you your IP address (You must allow DMs from the bot in order to use this command as your IP address needs to be sent privately) - [<a class="toolTipC" href="https://en.wikipedia.org/wiki/IP_address" target="_blank" mbIdentifyAs="tooltip" data-placement="top" title="Takes you to Wikipedia so you can learn about IP Addresses">what's an IP address?</a>]</td>
  </tr> -->
  <tr>
    <td class="mb-usageBG">m.yoshi</td>
    <td class="mb-usageBG">Summon beeg yoshi</td>
  </tr>
</table>
<br>
<table class="mb">
  <tr>
    <th class="mb-ownerCommands">OWNER/DEVELOPER COMMANDS</th>
    <th class="mb-ownerCommands">USAGE &amp; INFO</th>
  </tr>
  <tr>
    <td class="mb-usageBG">m.checkvote</td>
    <td class="mb-usageBG">Displays the list of users who have upvoted MarksBot</td>
  </tr>
  <tr>
    <td class="mb-usageBG">m.eval [code]</td>
    <td class="mb-usageBG">Evaulates js code</td>
  </tr>
  <tr>
    <td class="mb-usageBG">m.gcguilds</td>
    <td class="mb-usageBG">Displays a list of guilds that are using the MarksBot Global Chat System</td>
  </tr>
  <tr>
    <td class="mb-usageBG">m.guilds</td>
    <td class="mb-usageBG">Displays a list of guilds the bot is on</td>
  </tr>
  <tr>
    <td class="mb-usageBG">m.kill</td>
    <td class="mb-usageBG">Instantly shut down the bot</td>
  </tr>
  <tr>
    <td class="mb-usageBG">m.leave [id]</td>
    <td class="mb-usageBG">Force the bot to leave the selected guild</td>
  </tr>
  <tr>
    <td class="mb-usageBG">m.messagechannel [id]</td>
    <td class="mb-usageBG">Send a message to a specific channel</td>
  </tr>
  <tr>
    <td class="mb-usageBG">m.nts</td>
    <td class="mb-usageBG">Send yourself a note</td>
  </tr>
</table>