<style type="text/css">
.fb  {border-collapse:collapse;border-spacing:0;}
.fb td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;}
.fb th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;}
.fb .topbar{background-color:#ffcc67;text-align:left;vertical-align:top}
.fb .fb-e2cs{background-color:#ffcc67;text-align:left}
.fb .fb-0lax{text-align:left;vertical-align:top}
.fb .fb-trusted{background-color:#32cb00;text-align:left;vertical-align:top}
.fb .fb-iffy{background-color:#ff0000;text-align:left;vertical-align:top}
.fb .fb-danger{background-color:#ffff00;text-align:left;vertical-align:top}
</style>
<center><table class="fb">
  <tr>
    <th class="fb-e2cs">Bot Name</th>
    <th class="fb-e2cs">Bot Description</th>
    <th class="topbar">Support Server</th>
    <th class="topbar">Rating</th>
  </tr>
  <tr>
    <td class="fb-0lax"><a href="https://discordbots.org/bot/455166272339181589" mbIdentifyAs="tooltip" data-placement="bottom" title="">Elara</a></td>
    <td class="fb-0lax">A multiple purpose bot that with Fun, Information, Moderation commands, And logging features.</td>
    <td class="fb-0lax"><a href="https://discord.gg/qafHJ63">Join Support Server</a></td>
    <td class="fb-trusted">Trusted</td>
  </tr>
 <tr>
    <td class="fb-0lax"><a href="https://greenbot.mwserver.co" target="_blank">GreenBot</a></td>
    <td class="fb-0lax">Fun commands, Mod/Admin commands to make your life easier, User can see what permissions,  and if your user does not have any one to talk to, my bot will talk to them and be their friend with <code>g!chat [message]</code></td>
    <td class="fb-0lax"><a href="https://discord.gg/vDMJnWQ">Join Support Server</td>
    <td class="fb-trusted">Trusted</td>
  </tr>
</table></center>