<table class="mb">
   <tr>
      <th class="mb-generalCommands">GENERAL COMMANDS</th>
      <th class="mb-generalCommands">USAGE &amp; INFO</th>
   </tr>
   <tr>
      <td class="mb-usageBG">m.8ball [question]</td>
      <td class="mb-usageBG">Consults the magic 8ball - example m.8ball are you here? </td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.afk [message]</td>
      <td class="mb-usageBG">Sets you to AFK, if someone tags you it will tell them you are AFK and display the message you set</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.ask [question]</td>
      <td class="mb-usageBG">Ask MarksBot a question - example m.ask is it raining outside?</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.avatar @user</td>
      <td class="mb-usageBG">Displays the avatar of the user you tagged or displays your own avatar if no user is tagged</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.bill</td>
      <td class="mb-usageBG">Generate a be like bill image</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.billme [name] [gender]</td>
      <td class="mb-usageBG">Generate a be like bill image with your name (m.billme Mark m | m.billme Abbie f)</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.bingo</td>
      <td class="mb-usageBG">Can be used when playing Bingo to help you scratch off your card</td>
   </tr>
   <!-- <tr>
      <td class="mb-usageBG">m.botemoji</td>
      
      <td class="mb-usageBG">Displays all the emoji the bot has access to - <b><font color="#ff0000">SCHEDULED FOR REMOVAL ON NEXT PATCH</font></b></td>
      
      </tr> -->
   <tr>
      <td class="mb-usageBG">m.dbl [mention or id]</td>
      <td class="mb-usageBG">Queries the Discord Bot List to give information on a user or bot</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.discord</td>
      <td class="mb-usageBG">Shows the current status of Discord</td>
   </tr>
   <td class="mb-usageBG">m.e [text]</td>
   <td class="mb-usageBG">Puts your text into an embed - example m.e Hello MarksBot</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.emoji</td>
      <td class="mb-usageBG">Displays the custom emoji on the server</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.emojisearch [text]</td>
      <td class="mb-usageBG">Search the bot for emoji matching the requested name</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.fc</td>
      <td class="mb-usageBG">Fingers crossed</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.fns</td>
      <td class="mb-usageBG">Shows the Fortnite Daily Shop</td>
   </tr>
   <tr>
      <td class="mb-usageBG">(*) m.fns2</td>
      <td class="mb-usageBG">Shows an interactive version of the Fortnite Daily Shop</td>
   </tr>
   <!--   <tr>
      <td class="mb-disabled"><s>m.gc [text]</s></td>
      
      <td class="mb-disabled">CURRENTLY DISABLED <s>Sends a global chat message - example m.gc Hello, what server are you in?</s></td>
      
      </tr> -->
   <tr>
      <td class="mb-usageBG">m.guildblacklist</td>
      <td class="mb-usageBG">Displays the IDS of the blacklisted guilds (These are servers where MarksBot will refuse to join)</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.help</td>
      <td class="mb-usageBG">Displays the command list</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.invite</td>
      <td class="mb-usageBG">Displays the invite link so you can invite MarksBot to your server</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.info</td>
      <td class="mb-usageBG">Displays how many servers MarksBot is on and how many users it is serving</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.lastseen @user</td>
      <td class="mb-usageBG">Displays when the tagged user was last active [shows "undefined" if the users has not been active since the bot last restarted]</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.morsecode [text]</td>
      <td class="mb-usageBG">Converts your message into morsecode - example m.morsecode sos</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.mybill [text]</td>
      <td class="mb-usageBG">Put your own text on Bill</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.ping</td>
      <td class="mb-usageBG">Check if the bot is reponding</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.quiz</td>
      <td class="mb-usageBG">Answer a general knowledge question</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.rc </td>
      <td class="mb-usageBG">Generates a rancom color and displays the DEC and HEX values</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.someone</td>
      <td class="mb-usageBG">Picks a random server member</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.spinner</td>
      <td class="mb-usageBG">How long will it spin for?</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.serverinfo</td>
      <td class="mb-usageBG">Displays current server information</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.stafflist</td>
      <td class="mb-usageBG">Shows the list of verified MarksBot staff members</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.todo</td>
      <td class="mb-usageBG">Shows you your todo list</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.todo+ [text]</td>
      <td class="mb-usageBG">Adds something to your todo list</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.todo- </td>
      <td class="mb-usageBG">Removes whichever entry you select from your todo list</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.todoclear</td>
      <td class="mb-usageBG">Removed everything from your todo list (confirmation is required)</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.userinfo @user</td>
      <td class="mb-usageBG">Displays information about the tagged users account or your own information if no user is tagged</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.uptime</td>
      <td class="mb-usageBG">Displays how long MarksBot has been up for since it's last reboot</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.vote</td>
      <td class="mb-usageBG">Checks if you are able to upvote MarksBot</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.yesno [text]</td>
      <td class="mb-usageBG">Ask a question and the bot will decide yes or no - example Should I make food?</td>
   </tr>
</table>
