<table class="mb">
  <tr>
    <th class="mb-mbStaff">MARKSBOT STAFF COMMANDS</th>
    <th class="mb-mbStaff">USAGE &amp; INFO</th>
  </tr>
  <tr>
    <td class="mb-usageBG">m.guildban [ID]</td>
    <td class="mb-usageBG">Adds a guild ID to the blacklist ,this prevents MarksBot from joining the guild</td>
  </tr>
  <tr>
    <td class="mb-usageBG">m.guildunban [ID]</td>
    <td class="mb-usageBG">Removes a guild ID from the blacklist, allowing MarksBot to join the guild</td>
  </tr>
  <tr>
    <td class="mb-usageBG">m.restart</td>
    <td class="mb-usageBG">Shutsdown and restarts MarksBot</td>
  </tr>
</table>
