<li class="active"><a href="index" mbIdentifyAs="tooltip" data-placement="bottom" title="Back to the homepage">Home</a></li>
<li><a href="support" mbIdentifyAs="tooltip" data-placement="bottom" title="Click here if you need support using MarksBot">Support</a></li>
<li><a href="https://discordapp.com/oauth2/authorize?client_id=417143274713776139&scope=bot&permissions=2080767191" mbIdentifyAs="tooltip" data-placement="bottom" title="Invite MarksBot to your Discord Server">Invite</a></li>
<li><a href="https://discordbots.org/bot/417143274713776139/vote" mbIdentifyAs="tooltip" data-placement="bottom" title="Upvote us on Discord Bot List - We appreciate it!">Upvote on DBL</a></li>
<li>
   <a href="#" onClick="changelog()" mbIdentifyAs="tooltip" data-placement="bottom" title="Shows recent changes to the website and MarksBot">Recent Changes</a>
   <!-- <li><a href="#" onClick="specialThanks()" mbIdentifyAs="tooltip" data-placement="bottom" title="See who made MarksBot possible">Credits</a> -->
<li><a href="/status" mbIdentifyAs="tooltip" data-placement="bottom" title="Check the service status here!">Status</a></li>
<li><a href="/friendly-bots" mbIdentifyAs="tooltip" data-placement="bottom" title="Recommended bots for your server">Other Bots</a></li>
