<table class="mb">
   <tr>
      <th class="mb-ownerCommands">OWNER/DEVELOPER COMMANDS</th>
      <th class="mb-ownerCommands">USAGE &amp; INFO</th>
   </tr>
   <tr>
      <td class="mb-usageBG">m.addstaff [ID]</td>
      <td class="mb-usageBG">Adds a user as a verified MarksBot Staff member</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.checkvote</td>
      <td class="mb-usageBG">Displays the list of users who have upvoted MarksBot</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.eval [code]</td>
      <td class="mb-usageBG">Evaulates js code</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.gcguilds</td>
      <td class="mb-usageBG">Displays a list of guilds that are using the MarksBot Global Chat System</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.guilds</td>
      <td class="mb-usageBG">Displays a list of guilds the bot is on</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.kill</td>
      <td class="mb-usageBG">Instantly shut down the bot</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.leave [id]</td>
      <td class="mb-usageBG">Force the bot to leave the selected guild</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.messagechannel [id]</td>
      <td class="mb-usageBG">Send a message to a specific channel</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.nts</td>
      <td class="mb-usageBG">Send yourself a note</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.removestaff</td>
      <td class="mb-usageBG">Removed a MarksBot staff member</td>
   </tr>
</table>
