<style type="text/css">
.mb  {border-collapse:collapse;border-spacing:0;}
.mb td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;}
.mb th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;}
.mb .mb-cmd_perm_info{background-color:#f3eec1;border-color:inherit;text-align:left;vertical-align:top}
.mb .mb-top_menu{background-color:#34cdf9;border-color:inherit;text-align:left;vertical-align:top}
.mb .mb-spacer{background-color:#dadada;border-color:inherit;text-align:left;vertical-align:top}
</style>
<table class="mb">
 <tr>
    <td class="mb-spacer" colspan="3"><center>GENERAL COMMANDS - FREE FOR ALL</center></td>
  </tr>
  <tr>
    <th class="mb-top_menu">Command</th>
    <th class="mb-top_menu">MarksBot Requires</th>
    <th class="mb-top_menu">You Require</th>
  </tr>
  <tr>
    <td class="mb-cmd_perm_info">m.8ball</td>
	<td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
  </tr>
  <tr>
    <td class="mb-cmd_perm_info">m.afk</td>
	<td class="mb-cmd_perm_info"><code>SEND_MESSAGES, EMBED_LINKS</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
  </tr>
  <tr>
    <td class="mb-cmd_perm_info">m.ask</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
  </tr>
  <tr>
    <td class="mb-cmd_perm_info">m.avatar</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, EMBED_LINKS</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
  </tr>
    <tr>
    <td class="mb-cmd_perm_info">m.bill</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
  </tr>
    <tr>
    <td class="mb-cmd_perm_info">m.billme</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
  </tr>
    <tr>
    <td class="mb-cmd_perm_info">m.bingo</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, EMBED_LINKS</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
  </tr>
    <tr>
    <td class="mb-cmd_perm_info">m.discord</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, EMBED_LINKS</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
  </tr>
    <tr>
    <td class="mb-cmd_perm_info">m.e</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, EMBED_LINKS</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
  </tr>
    <tr>
    <td class="mb-cmd_perm_info">m.emoji</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, EMBED_LINKS</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
  </tr>
    <tr>
    <td class="mb-cmd_perm_info">m.emote</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, EMBED_LINKS</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
  </tr>
    <tr>
    <td class="mb-cmd_perm_info">m.fc</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
  </tr>
    <tr>
    <td class="mb-cmd_perm_info">m.fns</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, EMBED_LINKS</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
  </tr>
    <tr>
    <td class="mb-cmd_perm_info">m.fns2</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, EMBED_LINKS</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
  </tr>
    <tr>
    <td class="mb-cmd_perm_info">m.guildblacklist</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
  </tr>
  <tr>
    <td class="mb-cmd_perm_info">m.help</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, EMBED_LINKS</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
  </tr>
    <tr>
    <td class="mb-cmd_perm_info">m.invite</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, EMBED_LINKS</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
  </tr>
    <tr>
    <td class="mb-cmd_perm_info">m.info</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
  </tr>
    <tr>
    <td class="mb-cmd_perm_info">m.lastseen</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, EMBED_LINKS</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
  </tr>
    <tr>
    <td class="mb-cmd_perm_info">m.morsecode</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, EMBED_LINKS</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
  </tr>
    <tr>
    <td class="mb-cmd_perm_info">m.mybill</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
  </tr>
    <tr>
    <td class="mb-cmd_perm_info">m.ping</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
  </tr>
    <tr>
    <td class="mb-cmd_perm_info">m.quiz</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, EMBED_LINKS</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
  </tr>
    <tr>
    <td class="mb-cmd_perm_info">m.rc</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, EMBED_LINKS</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
  </tr>
    <tr>
    <td class="mb-cmd_perm_info">m.someone</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
  </tr>
    <tr>
    <td class="mb-cmd_perm_info">m.spinner</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, EMBED_LINKS</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
  </tr>
    <tr>
    <td class="mb-cmd_perm_info">m.serverinfo</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, EMBED_LINKS</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
  </tr>
    <tr>
    <td class="mb-cmd_perm_info">m.stafflist</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
  </tr>
    <tr>
    <td class="mb-cmd_perm_info">m.userinfo</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, EMBED_LINKS</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
  </tr>
    <tr>
    <td class="mb-cmd_perm_info">m.uptime</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
  </tr>
    <tr>
    <td class="mb-cmd_perm_info">m.vote</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, EMBED_LINKS</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
  </tr>
    <tr>
    <td class="mb-cmd_perm_info">m.yesno</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, EMBED_LINKS</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES</code></td>
  </tr>
  <tr>
    <td class="mb-spacer" colspan="3"><center>ADMIN/MOD SECTION</td>
  </tr>
   <tr>
    <th class="mb-top_menu">Command</th>
    <th class="mb-top_menu">MarksBot Requires</th>
    <th class="mb-top_menu">You Require</th>
  </tr>
   <tr>
    <td class="mb-cmd_perm_info">m.addemoji</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, EMBED_LINKS, MANAGE_EMOJIS</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, MANAGE_EMOJIS</code></td>
  </tr>
   <tr>
    <td class="mb-cmd_perm_info">m.ban</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, EMBED_LINKS, BAN_MEMBERS</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, BAN_MEMBERS</code></td>
  </tr>
   <tr>
    <td class="mb-cmd_perm_info">m.blacklist</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, MANAGE_MESSAGES</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, MANAGE_MESSAGES</code></td>
  </tr>
  <tr>
    <td class="mb-cmd_perm_info">m.check</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, MANAGE_MESSAGES, EMBED_LINKS</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, MANAGE_MESSAGES</code></td>
  </tr>
  <tr>
    <td class="mb-cmd_perm_info">m.clearwarnings</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, MANAGE_MESSAGES</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, MANAGE_MESSAGES</code></td>
  </tr>
   <tr>
    <td class="mb-cmd_perm_info">m.idban</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, BAN_MEMBERS</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, BAN_MEMBERS</code></td>
  </tr>
   <tr>
    <td class="mb-cmd_perm_info">m.kick</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, KICK_MEMBERS, EMBED_LINKS</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, KICK_MEMBERS</code></td>
  </tr>
     <tr>
    <td class="mb-cmd_perm_info">m.mute</td>
    <td class="mb-cmd_perm_info"><code>MANAGE_CHANNELS, MANAGE_MESSAGES, MANAGE_ROLES, SEND_MESSAGES</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, MANAGE_MESSAGES</code></td>
  </tr>
     <tr>
    <td class="mb-cmd_perm_info">m.prune</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, MANAGE_MESSAGES EMBED_LINKS</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, MANAGE_MESSAGES</code></td>
  </tr>
    <!-- <tr>
    <td class="mb-cmd_perm_info">m.setprefix</td>
    <td class="mb-cmd_perm_info"><code>MANAGE_SERVER, SEND_MESSAGES, EMBED_LINKS</code></td>
    <td class="mb-cmd_perm_info"><code>MANAGE_SERVER, SEND_MESSAGES</code></td>
  </tr> -->
     <tr>
    <td class="mb-cmd_perm_info">m.softban</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, EMBED_LINKS, BAN_MEMBERS</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, BAN_MEMBERS</code></td>
  </tr>
     <tr>
    <td class="mb-cmd_perm_info">m.unblacklist</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, MANAGE_MESSAGES</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, MANAGE_MESSAGES</code></td>
  </tr>
     <tr>
    <td class="mb-cmd_perm_info">m.unmute</td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, KICK_MEMBERS, EMBED_LINKS</code></td>
    <td class="mb-cmd_perm_info"><code>SEND_MESSAGES, KICK_MEMBERS</code></td>
  </tr>
     <tr>
    <td class="mb-cmd_perm_info">m.warn</td>
    <td class="mb-cmd_perm_info">TBD</td>
    <td class="mb-cmd_perm_info">TBD</td>
  </tr>
     <tr>
    <td class="mb-cmd_perm_info">m.warnings</td>
    <td class="mb-cmd_perm_info">TBD</td>
    <td class="mb-cmd_perm_info">TBD</td>
  </tr>
    <tr>
    <td class="mb-spacer" colspan="3"><center>MORE COMING SOON</center></td>
  </tr>
</table>