<table class="mb">
   <tr>
      <th class="mb-userRequested">USER REQUESTED COMMANDS</th>
      <th class="mb-userRequested">USAGE &amp; INFO</th>
   </tr>
   <tr>
      <td class="mb-usageBG">m.google [search term]</td>
      <td class="mb-usageBG">Use MarksBot to search Google - example m.google download discord</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.imdb [movie] </td>
      <td class="mb-usageBG">Displays information about the movie you request</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.ipcheck [ip] </td>
      <td class="mb-usageBG">Displays information about the IP address you provided (can be sent to dm's or channel)</td>
   </tr>
   <tr>
      <td class="mb-usageBG">m.say [text] </td>
      <td class="mb-usageBG">MarksBot will repeat what you say to it</td>
   </tr>
   <!-- <tr>
      <td class="mb-usageBG">m.setprefix [new prefix]</td>
      
      <td class="mb-usageBG">Sets a new prefix for the current server - Example <code>m.setprefix t.</code></td>
      
      </tr> -->
   <tr>
      <td class="mb-usageBG">m.ud [word]</td>
      <td class="mb-usageBG">Search the urban dictionary - example m.ud test</td>
   </tr>
   <!-- <tr>
      <td class="mb-usageBG">m.yip</td>
      
      <td class="mb-usageBG">Queries the IP Stack API and DM's you your IP address (You must allow DMs from the bot in order to use this command as your IP address needs to be sent privately) - [<a class="toolTipC" href="https://en.wikipedia.org/wiki/IP_address" target="_blank" mbIdentifyAs="tooltip" data-placement="top" title="Takes you to Wikipedia so you can learn about IP Addresses">what's an IP address?</a>]</td>
      
      </tr> -->
   <tr>
      <td class="mb-usageBG">m.yoshi</td>
      <td class="mb-usageBG">Summon beeg yoshi</td>
   </tr>
</table>
